# Configuração Principal do FarmaBot Pro

app:
  name: "FarmaBot Pro"
  version: "1.0.0"
  environment: "production"
  timezone: "America/Sao_Paulo"
  language: "pt-BR"

# Configuração WhatsApp Business
whatsapp:
  api_version: "v18.0"
  webhook_verify_token: ${WEBHOOK_VERIFY_TOKEN}
  access_token: ${WHATSAPP_TOKEN}
  phone_number_id: ${WHATSAPP_PHONE_ID}
  business_account_id: ${WHATSAPP_BUSINESS_ID}
  
  # Configurações de mensagem
  message_window: 24 # horas
  typing_delay: 2000 # ms
  max_menu_items: 10
  
  # Templates padrão
  templates:
    welcome: "farmabot_boas_vindas"
    menu: "farmabot_menu_principal"
    order_confirm: "farmabot_confirma_pedido"

# Configuração Supabase
supabase:
  url: ${SUPABASE_URL}
  anon_key: ${SUPABASE_ANON_KEY}
  service_key: ${SUPABASE_SERVICE_KEY}
  
  # Pool de conexões
  pool:
    min: 2
    max: 10
    idle_timeout: 30000
  
  # Cache
  cache:
    products 